### ISSUE TITLE
TypeError: obj.done is not a function

### ISSUE THREAD

**Issue by DanilloCorvalan** [vigour-io/open#1]
<img width="827" alt="screen shot 2016-03-04 at 11 20 07" src="https://cloud.githubusercontent.com/assets/1444981/13524392/361fc2dc-e1fb-11e5-81e5-e981cdb2bd79.png">

**Comment by youzi** [comment]
+1
/cc @marcusbesjes

**Comment by ricksmit3000** [comment]
resolved in version 1.0.3
